const fileInput = document.getElementById("fileInput");
const fileList = document.getElementById("fileList");

const generateButton = document.getElementById("generateButton");
const buttonText = document.getElementById("buttonText");

const status = document.getElementById("status");
const statusText = document.getElementById("statusText");

const results = document.getElementById("results");
const questionContainer = document.getElementById("questionContainer");
const resultInfo = document.getElementById("resultInfo");


/* ==============================
   YOUR BACKEND URL
   ============================== */

const BACKEND_URL = "PASTE-YOUR-RENDER-BACKEND-URL-HERE";


/* ==============================
   FILE UPLOAD
   ============================== */

fileInput.addEventListener("change", () => {

    fileList.innerHTML = "";

    const files = Array.from(fileInput.files);

    if (files.length === 0) {
        return;
    }

    files.forEach(file => {

        const item = document.createElement("div");

        item.className = "file-item";

        const size =
            (file.size / 1024 / 1024).toFixed(2);

        item.innerHTML = `
            <span>📄 ${file.name}</span>
            <span class="file-size">${size} MB</span>
        `;

        fileList.appendChild(item);

    });

});


/* ==============================
   GENERATE
   ============================== */

generateButton.addEventListener("click", async () => {

    const files = fileInput.files;

    const subject =
        document.getElementById("subject").value;

    const chapter =
        document.getElementById("chapter").value;

    const questionType =
        document.getElementById("questionType").value;

    const board =
        document.getElementById("board").value;

    const startYear =
        document.getElementById("startYear").value;

    const endYear =
        document.getElementById("endYear").value;


    /* BASIC VALIDATION */

    if (files.length === 0) {
        alert("Please upload at least one question paper.");
        return;
    }

    if (!subject) {
        alert("Please select a subject.");
        return;
    }

    if (!chapter) {
        alert("Please select a chapter.");
        return;
    }


    /* SHOW LOADING */

    generateButton.disabled = true;

    buttonText.textContent = "AI is analyzing...";

    status.classList.remove("hidden");

    results.classList.add("hidden");


    try {

        statusText.textContent =
            "Connecting to Question AI...";


        /*
        We send the selected information
        to your Flask backend.
        */

        const question = `
Subject: ${subject}
Chapter: ${chapter}
Question Type: ${questionType}
Board: ${board}
Year Range: ${startYear} - ${endYear}

Please analyze the uploaded question paper information
and generate a useful result.
        `;


        const response = await fetch(
            `${BACKEND_URL}/ask`,
            {
                method: "POST",

                headers: {
                    "Content-Type": "application/json"
                },

                body: JSON.stringify({
                    question: question
                })
            }
        );


        if (!response.ok) {

            throw new Error(
                `Server error: ${response.status}`
            );

        }


        const data = await response.json();


        if (data.error) {

            throw new Error(data.error);

        }


        /* SHOW AI RESULT */

        results.classList.remove("hidden");

        resultInfo.textContent =
            "Generated by Question AI";

        questionContainer.innerHTML = "";


        const questionBox =
            document.createElement("div");

        questionBox.className = "question";


        questionBox.innerHTML = `
            <div class="question-number">
                🤖 AI Analysis
            </div>

            <div class="option">
                ${formatAIResult(data.result)}
            </div>
        `;


        questionContainer.appendChild(questionBox);


    } catch (error) {

        console.error(error);

        alert(
            "AI connection failed.\n\n" +
            error.message
        );

    }


    /* RESET BUTTON */

    status.classList.add("hidden");

    generateButton.disabled = false;

    buttonText.textContent =
        "🔍 Find Questions";

});


/* ==============================
   FORMAT AI RESULT
   ============================== */

function formatAIResult(text) {

    if (!text) {
        return "No result received.";
    }

    return text
        .replace(/\n/g, "<br>")
        .replace(/Chapter:/g, "<strong>Chapter:</strong>")
        .replace(/Topic:/g, "<br><strong>Topic:</strong>")
        .replace(/Question Type:/g, "<br><strong>Question Type:</strong>")
        .replace(/Difficulty:/g, "<br><strong>Difficulty:</strong>")
        .replace(/Explanation:/g, "<br><strong>Explanation:</strong>");

}
